'use client';

import { useState } from 'react';
import { AnalysisResponse } from '@/lib/types';
import { OverviewCard } from '@/components/OverviewCard';
import { RisksSection } from '@/components/RisksSection';
import { RecommendationsSection } from '@/components/RecommendationsSection';
import { MigrationPlan } from '@/components/MigrationPlan';
import { SampleCode } from '@/components/SampleCode';
import { PRDescription } from '@/components/PRDescription';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { motion, AnimatePresence } from 'framer-motion';
import {
  LayoutDashboard,
  ShieldAlert,
  Sparkles,
  Layers,
  Code2,
  GitPullRequest,
  Download,
  RotateCcw,
  Check,
  Terminal,
} from 'lucide-react';

interface ReportTabsProps {
  data: AnalysisResponse;
  onReset: () => void;
}

export function ReportTabs({ data, onReset }: ReportTabsProps) {
  const [activeTab, setActiveTab] = useState('overview');
  const [downloading, setDownloading] = useState(false);

  const handleDownloadMarkdown = () => {
    setDownloading(true);

    const mdContent = `# Migration Scout Analysis Report
**Repository:** ${data.repoName}  
**Date:** ${data.timestamp ? new Date(data.timestamp).toLocaleString() : new Date().toLocaleString()}  
**Complexity:** ${data.summary?.complexityScore || 'High'}  
**Estimated Effort:** ${data.summary?.migrationEffortEstimate || '2-3 Weeks'}

---

## 1. Stack Modernization Summary
- **Legacy Stack:** ${data.detectedStack?.language || 'Unknown'} (${data.detectedStack?.framework || 'Unknown'})
- **Recommended Target:** ${data.recommendedStack?.language || 'TypeScript'} (${data.recommendedStack?.framework || 'Next.js 15'})
- **Rationale:** ${data.recommendedStack?.rationale || 'N/A'}

---

## 2. Security & Outdated Packages
- **Security Vulnerabilities Count:** ${data.summary?.securityVulnerabilitiesCount || 0}
- **Outdated Dependencies:** ${data.summary?.deprecatedDepsCount || 0}

### Key Vulnerabilities Identified:
${(data.securityRisks || [])
  .map(
    (r) => `- **[${r.severity}] ${r.title}** (${r.category})\n  *Location:* ${r.location || 'N/A'}\n  *Remediation:* ${r.remediation}`
  )
  .join('\n\n')}

---

## 3. Migration Roadmap
${(data.migrationPlan || [])
  .map(
    (p) => `### Phase ${p.phase}: ${p.title} (${p.duration})
*Risk:* ${p.risk} | *Effort:* ${p.effort}
${p.description}
Tasks:
${p.tasks.map((t) => `  - [ ] ${t}`).join('\n')}`
  )
  .join('\n\n')}

---

## 4. PR Summary Template
\`\`\`markdown
${data.prDescription?.markdown || 'N/A'}
\`\`\`

---
*Report generated by Migration Scout Agent v1.0*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${data.repoName.replace('/', '-')}-migration-report.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setTimeout(() => setDownloading(false), 1500);
  };

  return (
    <div className="space-y-6">
      {/* Top Header Controls Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-xl bg-slate-900/90 border border-slate-800 shadow-xl backdrop-blur-md">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-lg bg-cyan-500/10 text-cyan-400 border border-cyan-500/20">
            <Terminal className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-bold text-slate-100 font-mono tracking-tight">{data.repoName}</h2>
              <Badge className="bg-emerald-500/10 text-emerald-400 border-emerald-500/30 text-[10px] font-mono">
                Analysis Complete
              </Badge>
            </div>
            <p className="text-xs text-slate-400 font-mono">
              Target: <span className="text-cyan-400">{data.recommendedStack?.framework || 'Next.js 15'}</span>
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2.5">
          <Button
            onClick={handleDownloadMarkdown}
            disabled={downloading}
            variant="outline"
            size="sm"
            className="border-cyan-500/30 hover:bg-cyan-950/40 text-cyan-300 font-mono text-xs gap-1.5"
          >
            {downloading ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span>Downloaded!</span>
              </>
            ) : (
              <>
                <Download className="w-3.5 h-3.5" />
                <span>Download Report (.md)</span>
              </>
            )}
          </Button>
          <Button
            onClick={onReset}
            variant="ghost"
            size="sm"
            className="text-slate-400 hover:text-slate-200 hover:bg-slate-800 font-mono text-xs gap-1.5"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            <span>New Scan</span>
          </Button>
        </div>
      </div>

      {/* Main Tabbed Interface */}
      <Tabs defaultValue="overview" value={activeTab} onValueChange={setActiveTab} className="w-full space-y-6">
        <TabsList className="bg-slate-900/90 border border-slate-800 p-1 rounded-xl w-full grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-1 h-auto">
          <TabsTrigger
            value="overview"
            className="data-[state=active]:bg-cyan-500 data-[state=active]:text-slate-950 font-mono text-xs py-2 rounded-lg flex items-center justify-center gap-1.5 transition-all"
          >
            <LayoutDashboard className="w-3.5 h-3.5" />
            <span>Overview</span>
          </TabsTrigger>
          <TabsTrigger
            value="risks"
            className="data-[state=active]:bg-cyan-500 data-[state=active]:text-slate-950 font-mono text-xs py-2 rounded-lg flex items-center justify-center gap-1.5 transition-all"
          >
            <ShieldAlert className="w-3.5 h-3.5" />
            <span>Risks & Deps</span>
          </TabsTrigger>
          <TabsTrigger
            value="recommendations"
            className="data-[state=active]:bg-cyan-500 data-[state=active]:text-slate-950 font-mono text-xs py-2 rounded-lg flex items-center justify-center gap-1.5 transition-all"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Proposals</span>
          </TabsTrigger>
          <TabsTrigger
            value="plan"
            className="data-[state=active]:bg-cyan-500 data-[state=active]:text-slate-950 font-mono text-xs py-2 rounded-lg flex items-center justify-center gap-1.5 transition-all"
          >
            <Layers className="w-3.5 h-3.5" />
            <span>Roadmap</span>
          </TabsTrigger>
          <TabsTrigger
            value="code"
            className="data-[state=active]:bg-cyan-500 data-[state=active]:text-slate-950 font-mono text-xs py-2 rounded-lg flex items-center justify-center gap-1.5 transition-all"
          >
            <Code2 className="w-3.5 h-3.5" />
            <span>Code Diff</span>
          </TabsTrigger>
          <TabsTrigger
            value="pr"
            className="data-[state=active]:bg-cyan-500 data-[state=active]:text-slate-950 font-mono text-xs py-2 rounded-lg flex items-center justify-center gap-1.5 transition-all"
          >
            <GitPullRequest className="w-3.5 h-3.5" />
            <span>PR Template</span>
          </TabsTrigger>
        </TabsList>

        {/* Tab Content Panels with Smooth Fade Animations */}
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.2 }}
          >
            <TabsContent value="overview" className="mt-0 focus-visible:outline-none">
              <OverviewCard data={data} />
            </TabsContent>

            <TabsContent value="risks" className="mt-0 focus-visible:outline-none">
              <RisksSection outdatedLibraries={data.outdatedLibraries} securityRisks={data.securityRisks} />
            </TabsContent>

            <TabsContent value="recommendations" className="mt-0 focus-visible:outline-none">
              <RecommendationsSection recommendations={data.recommendations} />
            </TabsContent>

            <TabsContent value="plan" className="mt-0 focus-visible:outline-none">
              <MigrationPlan migrationPlan={data.migrationPlan} />
            </TabsContent>

            <TabsContent value="code" className="mt-0 focus-visible:outline-none">
              <SampleCode sampleCode={data.sampleCode} />
            </TabsContent>

            <TabsContent value="pr" className="mt-0 focus-visible:outline-none">
              <PRDescription prDescription={data.prDescription} />
            </TabsContent>
          </motion.div>
        </AnimatePresence>
      </Tabs>
    </div>
  );
}
