'use client';

import { useState } from 'react';
import { AnalysisResponse } from '@/lib/types';
import { OverviewCard } from '@/components/OverviewCard';
import { RisksSection } from '@/components/RisksSection';
import { RecommendationsSection } from '@/components/RecommendationsSection';
import { MigrationPlan } from '@/components/MigrationPlan';
import { SampleCode } from '@/components/SampleCode';
import { PRDescription } from '@/components/PRDescription';
import { RoiCalculator } from '@/components/RoiCalculator';
import { PromptExporter } from '@/components/PromptExporter';
import { DependencyTree } from '@/components/DependencyTree';
import { DiffViewer } from '@/components/DiffViewer';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { motion, AnimatePresence } from 'framer-motion';
import {
  LayoutDashboard,
  ShieldAlert,
  Sparkles,
  Layers,
  Code2,
  GitPullRequest,
  Download,
  RotateCcw,
  Check,
  Terminal,
} from 'lucide-react';

interface ReportTabsProps {
  data: AnalysisResponse;
  onReset: () => void;
}

export function ReportTabs({ data, onReset }: ReportTabsProps) {
  const [activeTab, setActiveTab] = useState('overview');
  const [downloading, setDownloading] = useState(false);

  const handleDownloadMarkdown = () => {
    setDownloading(true);

    const mdContent = `# Migration Scout Analysis Report
**Repository:** ${data.repoName}  
**Date:** ${data.timestamp ? new Date(data.timestamp).toLocaleString() : new Date().toLocaleString()}  
**Complexity:** ${data.summary?.complexityScore || 'High'}  
**Estimated Effort:** ${data.summary?.migrationEffortEstimate || '2-3 Weeks'}

---

## 1. Stack Modernization Summary
- **Legacy Stack:** ${data.detectedStack?.language || 'Unknown'} (${data.detectedStack?.framework || 'Unknown'})
- **Recommended Target:** ${data.recommendedStack?.language || 'TypeScript'} (${data.recommendedStack?.framework || 'Next.js 15'})
- **Rationale:** ${data.recommendedStack?.rationale || 'N/A'}

---

## 2. Security & Outdated Packages
- **Security Vulnerabilities Count:** ${data.summary?.securityVulnerabilitiesCount || 0}
- **Outdated Dependencies:** ${data.summary?.deprecatedDepsCount || 0}

### Key Vulnerabilities Identified:
${(data.securityRisks || [])
  .map(
    (r) => `- **[${r.severity}] ${r.title}** (${r.category})\n  *Location:* ${r.location || 'N/A'}\n  *Remediation:* ${r.remediation}`
  )
  .join('\n\n')}

---

## 3. Migration Roadmap
${(data.migrationPlan || [])
  .map(
    (p) => `### Phase ${p.phase}: ${p.title} (${p.duration})
*Risk:* ${p.risk} | *Effort:* ${p.effort}
${p.description}
Tasks:
${p.tasks.map((t) => `  - [ ] ${t}`).join('\n')}`
  )
  .join('\n\n')}

---

## 4. PR Summary Template
\`\`\`markdown
${data.prDescription?.markdown || 'N/A'}
\`\`\`

---
*Report generated by Migration Scout Agent v1.0*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${data.repoName.replace('/', '-')}-migration-report.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setTimeout(() => setDownloading(false), 1500);
  };

  return (
    <div className="space-y-6">
      {/* Top Header Controls Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-2xl bg-card border border-border shadow-sm backdrop-blur-md">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-primary/10 text-primary border border-primary/20">
            <Terminal className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-bold text-foreground font-mono tracking-tight">{data.repoName}</h2>
              <Badge className="bg-emerald-600/10 text-emerald-800 border-emerald-600/30 text-[9px] font-mono font-bold uppercase tracking-wider">
                Analysis Complete
              </Badge>
            </div>
            <p className="text-[11px] text-muted-foreground font-mono">
              Target: <span className="text-primary font-bold">{data.recommendedStack?.framework || 'Next.js 15'}</span>
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2.5">
          <Button
            onClick={handleDownloadMarkdown}
            disabled={downloading}
            variant="outline"
            size="sm"
            className="border-primary/20 bg-primary/10 hover:bg-primary/20 text-primary font-mono text-[11px] uppercase tracking-wider font-bold gap-1.5 rounded-xl cursor-pointer"
          >
            {downloading ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-700" />
                <span>Downloaded!</span>
              </>
            ) : (
              <>
                <Download className="w-3.5 h-3.5" />
                <span>Download Report</span>
              </>
            )}
          </Button>
          <Button
            onClick={onReset}
            variant="ghost"
            size="sm"
            className="text-muted-foreground hover:text-foreground hover:bg-secondary font-mono text-[11px] uppercase tracking-wider font-bold gap-1.5 rounded-xl cursor-pointer"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            <span>New Scan</span>
          </Button>
        </div>
      </div>

      {/* Main Tabbed Interface */}
      <Tabs defaultValue="overview" value={activeTab} onValueChange={setActiveTab} className="w-full space-y-6">
        <TabsList className="bg-card border border-border p-1.5 rounded-2xl w-full flex flex-wrap sm:flex-nowrap items-center justify-start sm:justify-between gap-1.5 h-auto shadow-sm overflow-x-auto scrollbar-none">
          <TabsTrigger
            value="overview"
            className="data-[state=active]:bg-primary data-[state=active]:text-primary-foreground font-mono text-[11px] font-bold uppercase tracking-wider py-2.5 px-3.5 rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer text-muted-foreground hover:text-foreground shrink-0 flex-1"
          >
            <LayoutDashboard className="w-3.5 h-3.5" />
            <span>Overview</span>
          </TabsTrigger>
          <TabsTrigger
            value="risks"
            className="data-[state=active]:bg-primary data-[state=active]:text-primary-foreground font-mono text-[11px] font-bold uppercase tracking-wider py-2.5 px-3.5 rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer text-muted-foreground hover:text-foreground shrink-0 flex-1"
          >
            <ShieldAlert className="w-3.5 h-3.5" />
            <span>Risks & Deps</span>
          </TabsTrigger>
          <TabsTrigger
            value="recommendations"
            className="data-[state=active]:bg-primary data-[state=active]:text-primary-foreground font-mono text-[11px] font-bold uppercase tracking-wider py-2.5 px-3.5 rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer text-muted-foreground hover:text-foreground shrink-0 flex-1"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Proposals</span>
          </TabsTrigger>
          <TabsTrigger
            value="plan"
            className="data-[state=active]:bg-primary data-[state=active]:text-primary-foreground font-mono text-[11px] font-bold uppercase tracking-wider py-2.5 px-3.5 rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer text-muted-foreground hover:text-foreground shrink-0 flex-1"
          >
            <Layers className="w-3.5 h-3.5" />
            <span>Roadmap</span>
          </TabsTrigger>
          <TabsTrigger
            value="code"
            className="data-[state=active]:bg-primary data-[state=active]:text-primary-foreground font-mono text-[11px] font-bold uppercase tracking-wider py-2.5 px-3.5 rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer text-muted-foreground hover:text-foreground shrink-0 flex-1"
          >
            <Code2 className="w-3.5 h-3.5" />
            <span>AST Code</span>
          </TabsTrigger>
          <TabsTrigger
            value="pr"
            className="data-[state=active]:bg-primary data-[state=active]:text-primary-foreground font-mono text-[11px] font-bold uppercase tracking-wider py-2.5 px-3.5 rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer text-muted-foreground hover:text-foreground shrink-0 flex-1"
          >
            <GitPullRequest className="w-3.5 h-3.5" />
            <span>PR Spec</span>
          </TabsTrigger>
        </TabsList>

        {/* Tab Content Panels with Smooth Fade Animations */}
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.2 }}
            className="w-full pt-1"
          >
            <TabsContent value="overview" className="mt-0 focus-visible:outline-none space-y-6">
              <OverviewCard data={data} />
              <RoiCalculator linesOfCode={data.summary?.linesOfCode} complexityScore={data.summary?.complexityScore} />
            </TabsContent>

            <TabsContent value="risks" className="mt-0 focus-visible:outline-none">
              <RisksSection outdatedLibraries={data.outdatedLibraries} securityRisks={data.securityRisks} />
            </TabsContent>

            <TabsContent value="recommendations" className="mt-0 focus-visible:outline-none">
              <RecommendationsSection recommendations={data.recommendations} />
            </TabsContent>

            <TabsContent value="plan" className="mt-0 focus-visible:outline-none space-y-6">
              <DependencyTree
                repoName={data.repoName}
                primaryLanguage={data.detectedStack?.language}
                targetStack={data.recommendedStack?.framework}
              />
              <MigrationPlan migrationPlan={data.migrationPlan} />
            </TabsContent>

            <TabsContent value="code" className="mt-0 focus-visible:outline-none space-y-6">
              <DiffViewer
                filename={`${data.repoName.split('/')[1] || 'migration'}-ast-refactor.ts`}
                legacyCode={data.sampleCode?.[0]?.legacyCode}
                modernCode={data.sampleCode?.[0]?.modernCode}
              />
              <SampleCode sampleCode={data.sampleCode} />
              <PromptExporter
                repoName={data.repoName}
                detectedLanguage={data.detectedStack?.language}
                targetStack={data.recommendedStack?.framework}
                outdatedLibraries={data.outdatedLibraries}
              />
            </TabsContent>

            <TabsContent value="pr" className="mt-0 focus-visible:outline-none">
              <PRDescription prDescription={data.prDescription} />
            </TabsContent>
          </motion.div>
        </AnimatePresence>
      </Tabs>
    </div>
  );
}
